// Which of Minka's API operations this server implements, and which of those a
// recorded reference exchange confirms. Writes COVERAGE.md.
//
// The operation list comes from Minka's published OpenAPI spec in the docs mirror
// (MINKA_SPEC, default ../docs.minka.io/_raw/openapi.yaml); it is read, not vendored.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { parse } from 'yaml'
import { buildApp } from '../server/src/app.js'
import { MemoryStore } from '../server/src/store.js'

const SPEC = process.env.MINKA_SPEC ?? new URL('../../docs.minka.io/_raw/openapi.yaml', import.meta.url).pathname
const spec = parse(readFileSync(SPEC, 'utf8'))
const METHODS = ['get', 'post', 'put', 'patch', 'delete']

// Path templates compare by shape: every {param} / :param becomes {}.
const shape = (p: string) => p.replace(/\{[^}]+\}|:[^/]+/g, '{}').replace(/\\!/g, '!')

const ours = new Set<string>()
const app = buildApp({
  store: new MemoryStore(),
  onRoute: (m, url) => METHODS.includes(m.toLowerCase()) && ours.add(`${m.toLowerCase()} ${shape(url.replace(/^\/api\/v2/, ''))}`),
})
await app.ready()

// A route is confirmed when some fixture holds a reference exchange for it.
const confirmed = new Set<string>()
const fixtures = new URL('./fixtures/', import.meta.url)
const specShapes = Object.keys(spec.paths).map((p) => ({ p, re: new RegExp('^' + shape(p).replace(/[.*+?^$()|[\]\\]/g, '\\$&').replace(/\\\{\\\}|\{\}/g, '[^/]+') + '$') }))
// Bridge logs (*.bridge.jsonl) hold calls to bridges, not ledger routes.
for (const f of readdirSync(fixtures).filter((f) => f.endsWith('.reference.jsonl'))) {
  for (const line of readFileSync(new URL(f, fixtures), 'utf8').trim().split('\n')) {
    const { req } = JSON.parse(line)
    const path = decodeURIComponent(req.url.replace(/^\/api\/v2/, '').split('?')[0])
    const hit = specShapes.find((s) => s.re.test(path))
    if (hit) confirmed.add(`${req.method.toLowerCase()} ${shape(hit.p)}`)
  }
}

type Row = { resource: string; method: string; path: string; summary: string; implemented: boolean; confirmed: boolean }
const rows: Row[] = []
for (const [path, item] of Object.entries<any>(spec.paths))
  for (const m of METHODS)
    if (item[m]) {
      const key = `${m} ${shape(path)}`
      rows.push({ resource: path.split('/')[1], method: m.toUpperCase(), path, summary: item[m].summary ?? '', implemented: ours.has(key), confirmed: confirmed.has(key) })
    }

const done = rows.filter((r) => r.implemented)
const byResource = new Map<string, Row[]>()
for (const r of rows) byResource.set(r.resource, [...(byResource.get(r.resource) ?? []), r])

const out: string[] = [
  '# API coverage',
  '',
  `Generated by \`npx tsx conformance/coverage.ts\` from Minka's published OpenAPI spec (${spec.info?.version}).`,
  '',
  `**${done.length} of ${rows.length}** operations implemented; ${done.filter((r) => r.confirmed).length} of them confirmed by a recorded reference exchange.`,
  '',
  '| Resource | Implemented | Operations |',
  '| --- | --- | --- |',
  ...[...byResource].sort((a, b) => b[1].filter((r) => r.implemented).length - a[1].filter((r) => r.implemented).length || a[0].localeCompare(b[0]))
    .map(([res, rs]) => `| ${res} | ${rs.filter((r) => r.implemented).length}/${rs.length} | ${rs.filter((r) => r.implemented).map((r) => `\`${r.method} ${r.path}\`${r.confirmed ? ' ✓' : ''}`).join('<br>') || '—'} |`),
  '',
  '✓ = a reference exchange for this operation is recorded in `conformance/fixtures/`.',
  '',
]
writeFileSync(new URL('../COVERAGE.md', import.meta.url), out.join('\n'))
const unconfirmed = [...ours].filter((k) => !rows.some((r) => `${r.method.toLowerCase()} ${shape(r.path)}` === k))
console.log(`${done.length}/${rows.length} implemented, ${done.filter((r) => r.confirmed).length} confirmed${unconfirmed.length ? `; not in spec: ${unconfirmed.join(', ')}` : ''}`)
