// What we sent to the Minka sandbox, kept for good. Every `run.sh record` appends a
// `start` and an `end` line to conformance/footprint.jsonl, kept or discarded alike;
// earlier recordings were backfilled from git history and session transcripts.
// docs/sandbox-footprint.md is rendered from the log.
//
//   tsx conformance/footprint.ts start <run> <level> <reference>
//   tsx conformance/footprint.ts end <run> <level> <exit> <fixture> [bridge-fixture]
//   tsx conformance/footprint.ts render     rewrite docs/sandbox-footprint.md
//   tsx conformance/footprint.ts verify     every recorded ledger is logged, the doc is current
//   tsx conformance/footprint.ts attest <statement…>   sign a statement with the operator key
import { appendFileSync, existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { createPrivateKey, createPublicKey, sign, verify } from 'node:crypto'
import { defaultOperatorKeyFile, loadOrCreateOperatorKey } from './identity.js'

const LOG = new URL('./footprint.jsonl', import.meta.url).pathname
const DOC = new URL('../docs/sandbox-footprint.md', import.meta.url).pathname
const FIXTURES = new URL('./fixtures/', import.meta.url).pathname

type Entry = {
  event: 'start' | 'end' | 'backfill'
  run: string
  ledger: string
  level: string
  at: string
  reference?: string
  operator?: string
  sdk?: string
  exit?: number
  exchanges?: number | null
  bridgeCalls?: number | null
  source?: string
  note?: string
}

const read = (): Entry[] =>
  existsSync(LOG) ? readFileSync(LOG, 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l)) : []
const append = (e: Entry) => appendFileSync(LOG, JSON.stringify(e) + '\n')
const lines = (f?: string) => (f && existsSync(f) ? readFileSync(f, 'utf8').split('\n').filter(Boolean) : [])
const sdkVersion = () => {
  try {
    return JSON.parse(readFileSync(new URL('../node_modules/@minka/ledger-sdk/package.json', import.meta.url), 'utf8')).version
  } catch {
    return undefined
  }
}

// Ed25519 from the SDK's raw base64 pair, through JWK.
const b64url = (b64: string) => Buffer.from(b64, 'base64').toString('base64url')
const privateKey = (k: { public: string; secret: string }) =>
  createPrivateKey({ key: { kty: 'OKP', crv: 'Ed25519', d: b64url(k.secret), x: b64url(k.public) }, format: 'jwk' })
const publicKey = (pub: string) => createPublicKey({ key: { kty: 'OKP', crv: 'Ed25519', x: b64url(pub) }, format: 'jwk' })

/** Ledgers named in the current fixtures. */
function recordedLedgers(): Map<string, string> {
  const out = new Map<string, string>()
  for (const f of readdirSync(FIXTURES).filter((f) => f.endsWith('.reference.jsonl'))) {
    const m = readFileSync(FIXTURES + f, 'utf8').match(/open-ledger-conf-\d{17}/)
    if (m) out.set(m[0], f.replace('.reference.jsonl', ''))
  }
  return out
}

function render(): string {
  const current = recordedLedgers()
  const runs = new Map<string, { start?: Entry; end?: Entry; back?: Entry }>()
  for (const e of read()) {
    const r = runs.get(e.run) ?? {}
    if (e.event === 'start') r.start = e
    else if (e.event === 'end') r.end = e
    else r.back = e
    runs.set(e.run, r)
  }
  const rows = [...runs.values()]
    .map((r) => {
      const s = r.start ?? r.back!
      const exchanges = r.end?.exchanges ?? r.back?.exchanges ?? null
      const bridge = r.end?.bridgeCalls ?? r.back?.bridgeCalls ?? null
      const outcome = r.back
        ? r.back.source ?? 'backfill'
        : r.end
          ? r.end.exit === 0 ? 'run.sh, ok' : `run.sh, exit ${r.end.exit}`
          : 'run.sh, no end line'
      return { s, exchanges, bridge, outcome, note: r.back?.note ?? '', kept: current.get(s.ledger) === s.level }
    })
    .sort((a, b) => a.s.at.localeCompare(b.s.at))
  const sum = (k: 'exchanges' | 'bridge') => rows.reduce((n, r) => n + (r[k] ?? 0), 0)
  const unknown = rows.filter((r) => r.exchanges == null).length
  const operators = [...new Set(rows.map((r) => r.s.operator).filter(Boolean))]
  const out = [
    '# Sandbox footprint',
    '',
    'Generated by `npx tsx conformance/footprint.ts render` from `conformance/footprint.jsonl`;',
    'do not edit by hand. Every ledger listed was created on the Minka sandbox',
    '(`https://ldg-stg.one`) by this project. The sandbox cannot drop ledgers, so they are all still there.',
    '',
    `**${rows.length} ledgers, ${sum('exchanges')} recorded requests from us, ${sum('bridge')} calls from the sandbox to our bridges.**`,
    unknown ? `${unknown} runs have no request count (not kept in git; see the note).` : '',
    'Requests are those that went through the recording proxy; polling that bypasses it',
    '(`DIRECT`, to wait for an intent to settle) is not counted, so the totals are a lower bound.',
    '',
    '## Operator key',
    '',
    operators.length
      ? `Since the log began, recorded ledgers are created by ${operators.map((o) => `\`${o}\``).join(', ')}. ` +
        'The secret is kept outside the repo; `footprint.ts attest` signs a statement with it.'
      : 'No run has used the operator key yet.',
    'Earlier ledgers (backfilled) were created with throwaway keys; they are tied to this project only through',
    'the git history of `conformance/fixtures/`.',
    '',
    '## Runs',
    '',
    '| Started (UTC) | Ledger | Level | Requests | Bridge calls | Source | Current fixture | Note |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...rows.map((r) =>
      `| ${r.s.at.slice(0, 16).replace('T', ' ')} | \`${r.s.ledger}\` | ${r.s.level} | ${r.exchanges ?? '?'} | ${r.bridge ?? ''} | ${r.outcome} | ${r.kept ? 'yes' : ''} | ${r.note} |`,
    ),
    '',
  ]
  return out.filter((l, i) => l !== '' || out[i - 1] !== '').join('\n')
}

/**
 * Further ledgers a scenario creates, by the suffix it gives the run's ledger handle
 * (`// footprint-ledger: -mint` in the scenario); each is logged as a run of its own.
 */
const extraLedgers = (level: string): string[] => {
  const f = new URL(`./scenarios/${level}.ts`, import.meta.url).pathname
  return existsSync(f) ? [...readFileSync(f, 'utf8').matchAll(/^\/\/ footprint-ledger: (\S+)$/gm)].map((m) => m[1]) : []
}

const [cmd, ...args] = process.argv.slice(2)
if (cmd === 'start') {
  const [run, level, reference] = args
  const key = await loadOrCreateOperatorKey(process.env.OPEN_LEDGER_OPERATOR_KEY ?? defaultOperatorKeyFile())
  for (const suffix of ['', ...extraLedgers(level)])
    append({ event: 'start', run: run + suffix, ledger: `open-ledger-conf-${run}${suffix}`, level, at: new Date().toISOString(), reference, operator: key.public, sdk: sdkVersion() })
} else if (cmd === 'end') {
  const [run, level, exit, fixture, bridge] = args
  const extra = extraLedgers(level)
  for (const suffix of ['', ...extra]) {
    const ledger = `open-ledger-conf-${run}${suffix}`
    // The run's own ledger counts the exchanges no further ledger claims.
    const of = (l: string) => (suffix ? l.includes(ledger) : l.includes(ledger) && !extra.some((x) => l.includes(ledger + x)))
    append({
      event: 'end', run: run + suffix, ledger, level, at: new Date().toISOString(), exit: Number(exit),
      exchanges: lines(fixture).filter(of).length,
      bridgeCalls: bridge && !suffix ? lines(bridge).length : null,
    })
  }
  writeFileSync(DOC, render())
} else if (cmd === 'render') {
  writeFileSync(DOC, render())
} else if (cmd === 'verify') {
  const logged = new Set(read().map((e) => e.ledger))
  const missing = [...recordedLedgers()].filter(([l]) => !logged.has(l))
  const stale = !existsSync(DOC) || readFileSync(DOC, 'utf8') !== render()
  for (const [l, level] of missing) console.error(`not in footprint.jsonl: ${l} (${level})`)
  if (stale) console.error('docs/sandbox-footprint.md is stale: run `npx tsx conformance/footprint.ts render`')
  if (missing.length || stale) process.exit(1)
  console.log(`footprint: ${logged.size} ledgers logged, every recorded one included`)
} else if (cmd === 'attest') {
  const file = process.env.OPEN_LEDGER_OPERATOR_KEY ?? defaultOperatorKeyFile()
  if (!existsSync(file)) throw new Error(`no operator key at ${file}`)
  const key = await loadOrCreateOperatorKey(file)
  const statement = args.join(' ')
  if (!statement) throw new Error('attest needs a statement')
  const signature = sign(null, Buffer.from(statement), privateKey(key)).toString('base64')
  if (!verify(null, Buffer.from(statement), publicKey(key.public), Buffer.from(signature, 'base64'))) throw new Error('self-check failed')
  console.log(JSON.stringify({ statement, method: 'ed25519', public: key.public, signature }, null, 2))
} else {
  console.error('usage: footprint.ts start|end|render|verify|attest')
  process.exit(2)
}
